### ISSUE TITLE
I'm not able to restart IntelliJ Community 13.1.1 after the installation of this plugin

### ISSUE THREAD

**Issue by francknouama** [yeungda/coffeescript-idea#12]
I had to reinstall IntelliJ and this is the report that got from the previous error:

com/intellij/psi/impl/source/tree/PlainTextFileElement: com/intellij/psi/impl/source/tree/PlainTextFileElement
java.lang.NoClassDefFoundError: com/intellij/psi/impl/source/tree/PlainTextFileElement
    at coffeescript.lang.ParserDefinition$1.parse(Unknown Source)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:44)
    at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:787)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:444)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:401)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.findElementAtInRoot(CollectHighlightsUtil.java:158)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.findCommonParent(CollectHighlightsUtil.java:139)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.getElementsInRange(CollectHighlightsUtil.java:53)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.getElementsInRange(CollectHighlightsUtil.java:45)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:64)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:380)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:371)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:368)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:193)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.impl.source.tree.PlainTextFileElement PluginClassLoader[coffeescript-idea, 0.1-1-gae5a]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 29 more

**Comment by comonad** [comment]
that plugin **coffeescript-idea 0.1-1-gae5a** is obsolete. use **CoffeeScript 2.0** instead.

had the same problem.
*IntelliJ IDEA Ultimate, 14.1.3*
